name: "infra preview & deploy"

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello Tastylog"
